/**
 * @file Orderbook.h
 * @brief Price-time priority orderbook implementation.
 * 
 * Implements a central limit orderbook with price-time priority matching.
 * Supports LIMIT, MARKET, and IOC order types.
 */

#ifndef ORDERBOOK_H
#define ORDERBOOK_H

#include <cstddef>
#include <functional>
#include <map>
#include <memory>
#include <unordered_map>
#include <vector>

#include "Order.h"

/**
 * @class Orderbook
 * @brief Central limit orderbook with price-time priority matching.
 * 
 * The Orderbook maintains separate bid and ask books, sorted by price.
 * Orders at the same price level are matched in FIFO order.
 * 
 * @par Matching Algorithm
 * 1. Incoming order is matched against contra book
 * 2. Best prices are matched first (highest bid, lowest ask)
 * 3. At each price level, orders are matched in time priority
 * 4. Remaining quantity is booked (LIMIT) or cancelled (MARKET/IOC)
 * 
 * @par Order Types
 * - LIMIT: Rest in book if not fully matched
 * - MARKET: Match at any price, cancel remainder
 * - IOC: Match immediately, cancel remainder
 */
class Orderbook
{
public:
    /**
     * @struct Trade
     * @brief Represents a single trade execution.
     */
    struct Trade {
        Timestamp timestamp{0};     ///< Trade execution timestamp
        OrderId buyOrderId{0};      ///< Buy order ID
        OrderId sellOrderId{0};     ///< Sell order ID
        Price price{0};             ///< Execution price
        Quantity quantity{0};       ///< Executed quantity
        TradeType tradeType{TradeType::DEFAULT};  ///< Trade type (PARTIAL/FULL)
    };

    using Trades = std::vector<Trade>;

    /**
     * @brief Construct a new Orderbook.
     */
    Orderbook();
    
    /**
     * @brief Destructor.
     */
    ~Orderbook();

    /**
     * @brief Add an order to the orderbook.
     * 
     * The order will be matched against the contra book first.
     * Any remaining quantity will be added to the appropriate book
     * (for LIMIT orders) or cancelled (for MARKET/IOC orders).
     * 
     * @param order Shared pointer to the order.
     */
    void AddOrder(const OrderPointer& order);
    
    /**
     * @brief Modify an existing order's price and/or quantity.
     * 
     * The order is removed from its current position and re-added
     * with new parameters. This may trigger new matches if the
     * price becomes more aggressive.
     * 
     * @param orderId ID of order to modify.
     * @param newPrice New order price.
     * @param newQuantity New order quantity.
     */
    void ModifyOrder(OrderId orderId, Price newPrice, Quantity newQuantity);
    
    /**
     * @brief Cancel an existing order.
     * 
     * Removes the order from the book and updates level data.
     * 
     * @param orderId ID of order to cancel.
     */
    void CancelOrder(OrderId orderId);
    
    /**
     * @brief Print orderbook to stdout for debugging.
     */
    void PrintOrderbook() const;
    
    /**
     * @brief Get trades from most recent order operation.
     * @return Vector of trades generated by last AddOrder/ModifyOrder.
     */
    const Trades& GetRecentTrades() const { return trades; }
    
    /**
     * @brief Clear the recent trades vector.
     */
    void ClearRecentTrades() { trades.clear(); }

private:
    /**
     * @struct LevelData
     * @brief Aggregate data for a price level.
     */
    struct LevelData {
        Price price{0};
        Quantity totalQuantity{0};
        std::size_t numberOfOrders{0};
    };

    using BidBook = std::map<Price, OrderPointers, std::greater<Price>>;
    using AskBook = std::map<Price, OrderPointers, std::less<Price>>;
    
    std::unordered_map<Price, LevelData> price_to_leveldata_;
    std::unordered_map<OrderId, OrderPointer> orders_;
    BidBook bids_;
    AskBook asks_;
    Trades trades;

    Trades matchOrder(const OrderPointer& incomingOrder);
    bool priceCrossed(Price incomingPrice, Price restingPrice, BuySell side, OrderType type) const;
    void addToBook(const OrderPointer& order);
    void updateLevelOnAdd(Price price, Quantity quantity);
    void updateLevelOnFill(Price price, Quantity quantity, bool orderClosed);
    void removeOrderFromBook(const OrderPointer& order);
    void clearOrderRecord(OrderId orderId);
};

#endif // ORDERBOOK_H